### ISSUE TITLE
Herramientas de desarrollo.

### ISSUE THREAD

**Issue by 5up3rD4n1** [DUXEL/sandbox#2]
Buscar una herramienta que se adapte mejor a las necesidades del proyecto (¿Cuales son?).

@melalonso @Luis-Ex @diugalde

**Comment by iamdeit** [comment]
Android Studio -> http://developer.android.com/sdk/index.html
                                           vs
Eclipse -> http://developer.android.com/tools/sdk/eclipse-adt.html

**Comment by 5up3rD4n1** [comment]
Yo he intentado android studio, y no se porqué la compu se pega toda y cuesta un montón utilizarla, es al menos la experiencia que he tenido con eso. No sé si soy yo o si es muy pesado o no sé. Pero siempre que he intentado utilizarlo para hacer pruebas y medio aprender algo no he podido.

**Comment by iamdeit** [comment]
Yo lo había usado en Windows sin problema alguno, voy a probar en Debian.
Cómo le fue con Eclipse?
